"""empty message

Revision ID: f20907acd8cc
Revises: 81da0e163875
Create Date: 2022-11-13 15:44:01.189081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20907acd8cc'
down_revision = '81da0e163875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_id', sa.String(length=32), nullable=False))
    op.create_unique_constraint(None, 'users', ['token_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'token_id')
    # ### end Alembic commands ###
