"""empty message

Revision ID: f4260d94949c
Revises: 70fef4c898cd
Create Date: 2022-11-17 16:08:08.380172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4260d94949c'
down_revision = '70fef4c898cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_id', sa.String(length=32), nullable=False))
    op.create_unique_constraint(None, 'users', ['token_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'token_id')
    # ### end Alembic commands ###
